branches:
  only:
    - main
matrix:
  fast_finish: true
  include:
  - language: go
    go: 1.11
    install: true
    before_script:
      - go vet ./slidechain/...
      - test `gofmt -s -l ./slidechain | grep -vF /vendor/ | wc -l` -eq 0
    script:
      - go test -v ./slidechain/... -timeout 60m
  - language: rust
    rust: nightly-2018-12-31
    cache: cargo
    before_script:
    - cd zkvm
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONTRUNBENCHMARKS"
  - language: rust
    rust: nightly-2018-12-31
    cache: cargo
    before_script:
    - cd spacesuit
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check
    - cargo test
    - RUSTFLAGS="-C opt-level=0" cargo bench "DONTRUNBENCHMARKS"

# About DONTRUNBENCHMARKS:
# This is a filter string that matches none of the benchmarks, therefore not causing Travis
# to waste time running benchmarks, but simply ensures that the benchmark builds are not broken.
# For the same reason, RUSTFLAGS="-C opt-level=0" are used: so the benchmarks are built faster.